DECLARE @directory NVARCHAR(max) = N'C:\Users\Sevon';
DECLARE @db_name NVARCHAR(MAX) = N'Coaches';

DECLARE @db_filename NVARCHAR(MAX) = CONCAT(@directory, '\', @db_name, '.mdf')
DECLARE @db_log_name NVARCHAR(MAX) = CONCAT(@db_name, '_log')
DECLARE @db_log_filename NVARCHAR(MAX) = CONCAT(@directory, '\', @db_log_name, '.ldf')


USE [master]
DROP DATABASE IF EXISTS [Coaches]
/****** Object:  Database [Coaches]    Script Date: 18.03.2021 11:40:48 ******/
DECLARE @sql_db_create NVARCHAR(MAX) = N'
CREATE DATABASE [Coaches]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'''+@db_name+''', FILENAME = N'''+@db_filename+''' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'''+@db_log_name+''', FILENAME = N'''+@db_log_filename+''' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
';
EXEC sp_executesql @sql_db_create

GO
ALTER DATABASE [Coaches] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Coaches].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Coaches] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Coaches] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Coaches] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Coaches] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Coaches] SET ARITHABORT OFF 
GO
ALTER DATABASE [Coaches] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Coaches] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Coaches] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Coaches] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Coaches] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Coaches] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Coaches] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Coaches] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Coaches] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Coaches] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Coaches] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Coaches] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Coaches] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Coaches] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Coaches] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Coaches] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Coaches] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Coaches] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Coaches] SET  MULTI_USER 
GO
ALTER DATABASE [Coaches] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Coaches] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Coaches] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Coaches] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Coaches] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Coaches] SET QUERY_STORE = OFF
GO
USE [Coaches]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Coaches]
GO
/****** Object:  Table [dbo].[Coach]    Script Date: 18.03.2021 11:40:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Coach](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[Surname] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[PhoneNumber] [nvarchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Coaches] SET  READ_WRITE 
GO
